name: Build and deploy to GitHub pages for testing

on:
  push:
    branches:
      - dev # Trigger the action only on PR merges into dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm run build
          npm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: editioncrafter/storybook-static # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
